steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/youtube-tiktok-converter:$COMMIT_SHA', '-f', 'Dockerfile.simple', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/youtube-tiktok-converter:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'youtube-tiktok-converter'
    - '--image'
    - 'gcr.io/$PROJECT_ID/youtube-tiktok-converter:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/youtube-tiktok-converter:$COMMIT_SHA'
